# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux

#matrix:

#branches:
#  only:
#    - master

addons:
  apt:
    packages:
      - libbox2d-dev
      - libglm-dev
      - libsdl2-dev

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl openal-soft; fi

script:
# ALL THE BUILD COMMANDS HERE
  - export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;/usr/lib/x86_64-linux-gnu/"
  - CMAKE_OPTIONS='-DCMAKE_PREFIX_PATH='"$CMAKE_PREFIX_PATH"' -DCMAKE_BUILD_TYPE=RelWithDebInfo'
  - rm -rf cmake-build
  - mkdir cmake-build
  - cd cmake-build
  - cmake $CMAKE_OPTIONS ..
  - make -j 2

#notifications:
#  irc:
#    channels:
#      - "irc.esper.net#bitblot"
#    skip_join: true
#    use_notice: true
#    on_success: change
#    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
#      - "[%{repository_slug}#%{branch} @%{commit}] (%{author}): %{message}"
#      - "Diff: %{compare_url}"
#      - "Build: %{build_url}"
