# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux

branches:
  only:
    - ci

addons:
  apt:
    packages:
      - libbox2d-dev
      - libglm-dev
      - libsdl2-dev

before_install:
  - wget https://www.dropbox.com/s/61h7ziwo4fdk8xc/fmodstudioapi11002linux.tar.gz
  - tar -xzf fmodstudioapi11002linux.tar.gz
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl openal-soft; fi

script:
# ALL THE BUILD COMMANDS HERE
  - export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;/usr/lib/x86_64-linux-gnu/"
  - CMAKE_OPTIONS='-DCMAKE_PREFIX_PATH='"$CMAKE_PREFIX_PATH"' -DCMAKE_BUILD_TYPE=RelWithDebInfo'
  - rm -rf cmake-build
  - mkdir cmake-build
  - cd cmake-build
  - cmake $CMAKE_OPTIONS ..
  - make -j 2

notifications:
  email: false
