#include "Engine.h"

void Engine::addNode(Node* n)
{
	if(n != NULL)
	{
		m_nodes.push_back(n);
		n->init();
	}
}

void Engine::addObject(obj* o)
{
	if(o != NULL)
	{
		m_lObjects.push_back(o);
		o->initLua();
	}
}

/*/ This seems like a bad idea overall
void Engine::updateSceneryLayer(physSegment* seg)
{
	for(multiset<physSegment*>::iterator layer = m_lScenery.begin(); layer != m_lScenery.end(); layer++)
	{
		if((*layer) == seg)
		{
			m_lScenery.erase(layer);
			break;
		}
	}
	m_lScenery.insert(seg);
}*/

void Engine::drawAll()
{
	multimap<float, Drawable*> drawList;	//Depth matters, and some Drawables will be at different depths, so draw all in one pass

	for(multiset<physSegment*>::iterator i = m_lScenery.begin(); i != m_lScenery.end(); i++)	//Add bg layers
		drawList.insert(make_pair((*i)->depth, (Drawable*)(*i)));
		
	for(list<obj*>::iterator i = m_lObjects.begin(); i != m_lObjects.end(); i++)	//Add objects
		drawList.insert(make_pair((*i)->depth, (Drawable*)(*i)));
		
	for(list<ParticleSystem*>::iterator i = m_particles.begin(); i != m_particles.end(); i++)	//Add particles
		drawList.insert(make_pair((*i)->depth, (Drawable*)(*i)));
		
	//Draw everything in one pass
	for(multimap<float, Drawable*>::iterator i = drawList.begin(); i != drawList.end(); i++)
		i->second->draw();
}

void Engine::cleanupObjects()
{
	for(list<obj*>::iterator i = m_lObjects.begin(); i != m_lObjects.end(); i++)
		delete (*i);
	for(multiset<physSegment*>::iterator i = m_lScenery.begin(); i != m_lScenery.end(); i++)
		delete (*i);
	for(list<Node*>::iterator i = m_nodes.begin(); i != m_nodes.end(); i++)
		delete (*i);
	m_lScenery.clear();
	m_lObjects.clear();
	m_nodes.clear();
	
	//Wipe Box2D physics data that's left over
	list<b2Body*> bodies;
	for(b2Body* bod = m_physicsWorld->GetBodyList(); bod != NULL; bod = bod->GetNext())
		bodies.push_back(bod);
	
	for(list<b2Body*>::iterator i = bodies.begin(); i != bodies.end(); i++)
		m_physicsWorld->DestroyBody(*i);
}

void Engine::updateObjects(float32 dt)
{
	//Update objects
	list<b2BodyDef*> lAddObj;	//For holding objects generated by these objects updating
	for(list<obj*>::iterator i = m_lObjects.begin(); i != m_lObjects.end(); i++)
	{
		b2BodyDef* def = (*i)->update(dt);
		if(def != NULL)
			lAddObj.push_back(def);
	}
	//Add generated objects
	for(list<b2BodyDef*>::iterator i = lAddObj.begin(); i != lAddObj.end(); i++)
	{
		objFromXML(*((string*)(*i)->userData), (*i)->position, (*i)->linearVelocity);
		delete (*i);	//Free up memory
	}
	//Update nodes
	for(list<Node*>::iterator i = m_nodes.begin(); i != m_nodes.end(); i++)
	{
		(*i)->update(dt);
	}
}

Node* Engine::getNode(string sNodeName)
{
	for(list<Node*>::iterator i = m_nodes.begin(); i != m_nodes.end(); i++)
	{
		if((*i)->name == sNodeName)
			return (*i);
	}
	return NULL;
}